### PR TITLE
add blender / MN install instructions

### PR DESCRIPTION
**Pull request by BradyAJohnston**
I provide a brief overview of the install instructions and link to the docs for more details. I can bring those details to this document if we want.

### CODE REVIEW

**Comment by jennaswa** [comment]
LGTM! Feel free to merge, unless @fiona-naughton, @lilyminium or @yuxuanzhuang have additional comments.

**Comment by lilyminium** [comment]
LGTM!

**Comment by BradyAJohnston** [comment]
I would merge but I don't have write access for this repo

**Comment by lilyminium** [comment]
Whoops, just added you now!

**Pull request merged**
